### ISSUE TITLE
Pick a cool name for this library

### ISSUE THREAD

**Issue by BigRoy** [BigRoy/env_prototype#1]
### Issue

We need a cool name. Period.

1. There shouldn't be Python library/package with the same name yet.
2. Something with `env` in it makes sense (not required though)
3. Something that fits with what it does, environment management.

### Ideas

- [envision](https://www.thefreedictionary.com/envision)
- [envoy](https://www.wordfind.com/word/envoy/)
- [abode](https://www.thefreedictionary.com/abode) (synonym to environment) - clashes with current [abodepy library](https://github.com/MisterWil/abodepy)

**Comment by aardschok** [comment]
How about:

* gaia / gaea (the greek name / embodiment for mother nature)
* [quanta](https://en.wikipedia.org/wiki/Quantum)
* orion (the constellation as the environment we make a collection of bodies ;) )
* ascent
* pantheon

**Comment by BigRoy** [comment]
Most of them seem hard to remember because of their complexity - also because they don't link too closely to `env` or `environment`. Orion is simple and cool, but there seem a lot of "orionsdk" or other surrounding python packages with a similar name - yet not one exactly orion.

Not sure. Maybe something comes up over the weekend.

**Comment by aardschok** [comment]
I just found this one: https://github.com/kennethreitz/envoy
Seems like envoy is off the table

**Comment by BigRoy** [comment]
Thanks.

How about `pyviron`? (Python environment)
Or `mansion`? (Like a nice huge house)
Or [`acre`](https://en.wikipedia.org/wiki/Acre)?
Or `envman`? The one and only environment _man_-ager.
Or `envpower`? Badum tss...
Or `prepare`? Pretty straight forward? And seems free
Or `prepenv`? Prepare-environment?
Or `envport`? Port the the environment, also close to "airport" which I think is nice ;)
Or `envportal`? Portal to the environment.

Or wait, this one...

`envology`?

I seem to be losing some naming superpowers here.

I also checked gaia, orion, pantheon - they all seem to clash unfortunately. Quanta is nice and short, but seems a bit too far from the link for me.

**Comment by aardschok** [comment]
I think `acre` is the winner here :)

**Comment by BigRoy** [comment]
Short and simple, let's give it a go.
